### PR TITLE
Added code for computing cost by getting user input.

### PR DESCRIPTION
**Pull request by manikyabard**
The added code is in the last cell of the notebook.

### CODE REVIEW

**Comment by amit-jha-cmd** [comment]
great work! @manikyabard. However, your computerCost2 function is calculating the cost(error) of the model and not the price. please note that computeCost function is calculating the error of the model and is not making any prediction. 
You have to find some other way to do it...
[hint: use theta from gradient descent function and make a vector of the user input together with bias value 1 then simply do matrix multiplication]

**Review by amit-jha-cmd — CHANGES_REQUESTED** [review]
replace the computeCost2 function with another function. It's not predicting the price but calculating the cost of the model.

**Comment by manikyabard** [comment]
Ok sorry, I got a bit confused.

**Comment by amit-jha-cmd** [comment]
> Ok sorry, I got a bit confused.

we are all learning. no need to apologise. relax.

**Comment by amit-jha-cmd** [comment]
thanks @manikyabard

**Pull request merged**
